# -*- coding: utf-8 -*-
from odoo import api, fields, models, _


class ProductAttribute(models.Model):
    _inherit = 'product.attribute'

    dnk_show_in_invoice = fields.Boolean(
        string='- Show in Sale Order and Invoice', default=True,
        help='If checked, this Attribute will be shown in Sale Order and Invoice Lines Description.', required=True)


class ProductTemplateAttributeValue(models.Model):
    """Materialized relationship between attribute values
    and product template generated by the product.template.attribute.line"""

    _inherit = "product.template.attribute.value"

    def _variant_name(self, variable_attributes):
        return ", ".join([v.name for v in self if v.attribute_id in variable_attributes])
